language: ruby
rvm:
  - 2.1.1
addons:
  postgresql: "9.3"
script:
  - bundle exec rake
before_script:
  - psql -c 'create database sample-database-test;' -U postgres
  - cp config/database.yml.sample config/database.yml
