language: ruby
rvm:
  - 2.1.1
before_script:
  - psql -c 'create database sample-database-test;' -U postgres
  - cp config/database.yml.sample config/database.yml
script:
  - bundle exec rake db:test:prepare
  - bundle exec rake
