# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3134228b6261b156dc772b01dc2b1df141dcc47708b9ce5f7b5f91a373d5e0d5942a0b23e1946225b36034d4975816a008d372b774f2393d185d9b8dfe067529
  admin_password: 0dbfb112168528b103b4f0993ba2b9ed76a877a6 # hashed "dev123"

test:
  secret_key_base: 468c2c1f371697f6646f0b715574f821618f117ebd71934a29b27fa24e918920714d814aff258ad7a0ee10d0beaa5459ef970cee18f938b556e3b8a402b6ed5a
  admin_password: 0dbfb112168528b103b4f0993ba2b9ed76a877a6 # hashed "dev123"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  admin_password: <%= ENV["GR_ADMIN_PASSWORD"] %>
